# Generated by Django 4.0.5 on 2022-06-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.dept'),
        ),
    ]
